'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvisDesktop', {
  platform: process.platform,
  capabilities: { recordedStt:true, remoteTts:true, gmailOAuth:false, cloudSync:false },
  invokeFunction: (name, payload) => ipcRenderer.invoke('jarvis:function:invoke', name, payload),
  getSystemContext: () => ipcRenderer.invoke('jarvis:system:context'),
  getRecentCrashes: (limit = 20) => ipcRenderer.invoke('jarvis:crash:recent', limit),
  reportRendererIssue: (report) => ipcRenderer.invoke('jarvis:crash:report', report),
  getRules: () => ipcRenderer.invoke('jarvis:policy:rules'),
  evaluateAction: (action) => ipcRenderer.invoke('jarvis:policy:evaluate', action),
  ownerOverride: (request) => ipcRenderer.invoke('jarvis:policy:override', request),
  getOwnerPinStatus: () => ipcRenderer.invoke('jarvis:policy:pin:status'),
  setOwnerPin: (request) => ipcRenderer.invoke('jarvis:policy:pin:set', request),
  elevatedDiagnostics: {
    status: () => ipcRenderer.invoke('jarvis:admin:status'),
    start: () => ipcRenderer.invoke('jarvis:admin:start'),
    snapshot: () => ipcRenderer.invoke('jarvis:admin:snapshot'),
    stop: () => ipcRenderer.invoke('jarvis:admin:stop'),
  },
  getSettings: () => ipcRenderer.invoke('jarvis:settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('jarvis:settings:save', settings),
  setTheme: (theme) => ipcRenderer.invoke('jarvis:theme:set', theme),
  listModels: () => ipcRenderer.invoke('jarvis:ai:list-models'),
  listSpeechModels: () => ipcRenderer.invoke('jarvis:ai:list-speech-models'),
  testAiConnection: (apiKey = '') => ipcRenderer.invoke('jarvis:ai:test-connection', { apiKey }),
  selectFiles: (options) => ipcRenderer.invoke('jarvis:file:select', options),
  oneClickUpdate: () => ipcRenderer.invoke('jarvis:update:one-click'),
  localDeviceRequest: (request) => ipcRenderer.invoke('jarvis:device:request', request),
  data: {
    filter: (entity, query, sort, limit) => ipcRenderer.invoke('jarvis:data:filter', { entity, query, sort, limit }),
    search: (entity, query, text, limit) => ipcRenderer.invoke('jarvis:data:search', { entity, query, text, limit }),
    create: (entity, data) => ipcRenderer.invoke('jarvis:data:create', { entity, data }),
    update: (entity, id, patch) => ipcRenderer.invoke('jarvis:data:update', { entity, id, patch }),
    delete: (entity, id) => ipcRenderer.invoke('jarvis:data:delete', { entity, id }),
    importLegacy: (snapshot) => ipcRenderer.invoke('jarvis:data:import-legacy', snapshot),
    stats: () => ipcRenderer.invoke('jarvis:data:stats'),
    getUser: () => ipcRenderer.invoke('jarvis:data:user:get'),
    updateUser: (patch) => ipcRenderer.invoke('jarvis:data:user:update', patch),
  },
  backup: {
    create: (passphrase) => ipcRenderer.invoke('jarvis:backup:create', { passphrase }),
    restore: (passphrase) => ipcRenderer.invoke('jarvis:backup:restore', { passphrase }),
  },
  runSystemCheck: () => ipcRenderer.invoke('jarvis:system:check'),
  repair: {
    plan: (report) => ipcRenderer.invoke('jarvis:repair:plan', report),
    apply: (repairId, reportId) => ipcRenderer.invoke('jarvis:repair:apply', { repairId, reportId }),
  },
  developerRepair: {
    getPending: () => ipcRenderer.invoke('jarvis:self-repair:manual:pending'),
    applyPending: (hash) => ipcRenderer.invoke('jarvis:self-repair:manual:apply', { hash }),
  },
  obd: {
    listPorts: () => ipcRenderer.invoke('jarvis:obd:list-ports'),
    connect: (options) => ipcRenderer.invoke('jarvis:obd:connect', options),
    send: (command, timeout) => ipcRenderer.invoke('jarvis:obd:send', { command, timeout }),
    status: () => ipcRenderer.invoke('jarvis:obd:status'),
    disconnect: () => ipcRenderer.invoke('jarvis:obd:disconnect'),
  },
});
