'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvisDesktop', {
  platform: process.platform,
  invokeFunction: (name, payload) => ipcRenderer.invoke('jarvis:function:invoke', name, payload),
  getSystemContext: () => ipcRenderer.invoke('jarvis:system:context'),
  openEmergencyCall: (number) => ipcRenderer.invoke('jarvis:system:open-emergency-call', number),
  getRules: () => ipcRenderer.invoke('jarvis:policy:rules'),
  evaluateAction: (action) => ipcRenderer.invoke('jarvis:policy:evaluate', action),
  ownerOverride: (request) => ipcRenderer.invoke('jarvis:policy:override', request),
  getSettings: () => ipcRenderer.invoke('jarvis:settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('jarvis:settings:save', settings),
  listModels: () => ipcRenderer.invoke('jarvis:ai:list-models'),
  listImageModels: () => ipcRenderer.invoke('jarvis:function:invoke', 'listImageModels', {}),
  selectFiles: (options) => ipcRenderer.invoke('jarvis:file:select', options),
  oneClickUpdate: () => ipcRenderer.invoke('jarvis:update:one-click'),
  getStabilityStatus: () => ipcRenderer.invoke('jarvis:stability:status'),
  runStabilitySelfTest: () => ipcRenderer.invoke('jarvis:stability:self-test'),
  openStabilityLogs: () => ipcRenderer.invoke('jarvis:stability:open-logs'),
  restartApp: () => ipcRenderer.invoke('jarvis:app:restart'),
  reportRuntimeError: (report) => ipcRenderer.invoke('jarvis:self-repair:report', report),
  listSelfRepairs: () => ipcRenderer.invoke('jarvis:self-repair:list'),
  approveSelfRepair: (id) => ipcRenderer.invoke('jarvis:self-repair:approve', id),
  rejectSelfRepair: (id) => ipcRenderer.invoke('jarvis:self-repair:reject', id),
  listOBDSerialPorts: () => ipcRenderer.invoke('jarvis:obd:serial:list'),
  connectOBDSerial: (options) => ipcRenderer.invoke('jarvis:obd:serial:connect', options),
  getOBDSerialStatus: () => ipcRenderer.invoke('jarvis:obd:serial:status'),
  sendOBDSerial: (request) => ipcRenderer.invoke('jarvis:obd:serial:send', request),
  disconnectOBDSerial: () => ipcRenderer.invoke('jarvis:obd:serial:disconnect'),
  getDataStatus: () => ipcRenderer.invoke('jarvis:data:status'),
  importLegacyData: (payload) => ipcRenderer.invoke('jarvis:data:import-legacy', payload),
  getLocalUser: () => ipcRenderer.invoke('jarvis:data:user:get'),
  updateLocalUser: (patch) => ipcRenderer.invoke('jarvis:data:user:update', patch),
  entityFilter: (entityName, query, sort, limit) => ipcRenderer.invoke('jarvis:data:entity:filter', entityName, query, sort, limit),
  entityCreate: (entityName, data) => ipcRenderer.invoke('jarvis:data:entity:create', entityName, data),
  entityUpdate: (entityName, rowId, patch) => ipcRenderer.invoke('jarvis:data:entity:update', entityName, rowId, patch),
  entityDelete: (entityName, rowId) => ipcRenderer.invoke('jarvis:data:entity:delete', entityName, rowId),
});
